import type { Bill } from "./types";

export const demoBill: Bill = {
  id: "bill_demo",
  shareId: "mesa-viernes",
  title: "Mesa viernes",
  imageUrl: "",
  ocrStatus: "success",
  expectedParticipantCount: 4,
  receiptSubtotal: 51400,
  receiptTip: 5140,
  receiptTotal: 54540,
  enteredSubtotal: 51400,
  enteredTip: 5140,
  enteredTotal: 54540,
  missingAmount: 0,
  subtotal: 51400,
  tip: 5140,
  serviceFee: 0,
  discount: 2000,
  total: 54540,
  status: "draft",
  paymentMethod: "mixed",
  paymentLink: "https://example.com/pagar",
  paymentQrUrl: "",
  receiverName: "Camila Rojas",
  bankName: "Banco Estado",
  accountType: "Cuenta Corriente",
  accountNumber: "123456789",
  receiverIdentifier: "12.345.678-9",
  paymentNote: "Mesa viernes",
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  items: [
    {
      id: "item_1",
      billId: "bill_demo",
      name: "Pizza margarita",
      quantity: 2,
      unitPrice: 8900,
      totalPrice: 17800,
      isShared: true,
      splitMode: "shared_by_claimants",
    },
    {
      id: "item_2",
      billId: "bill_demo",
      name: "Schop IPA",
      quantity: 4,
      unitPrice: 4500,
      totalPrice: 18000,
      isShared: false,
      splitMode: "unit",
    },
    {
      id: "item_3",
      billId: "bill_demo",
      name: "Papas rusticas",
      quantity: 1,
      unitPrice: 7200,
      totalPrice: 7200,
      isShared: true,
      splitMode: "shared_by_claimants",
    },
    {
      id: "item_4",
      billId: "bill_demo",
      name: "Limonada",
      quantity: 2,
      unitPrice: 4200,
      totalPrice: 8400,
      isShared: false,
      splitMode: "unit",
    },
  ],
  participants: [],
};
